# Text size settings
TEXT_SIZE_MIN = 8
TEXT_SIZE_MAX = 72
TEXT_SIZE_DEFAULT = 20

# Text angle settings
TEXT_ANGLE_MIN = -90
TEXT_ANGLE_MAX = 90
TEXT_ANGLE_DEFAULT = 0
TEXT_ANGLE_TICK_INTERVAL = 15

# Preview settings
PREVIEW_SIZE = 60
PREVIEW_SAMPLE_TEXT = "Aa"
PREVIEW_FONT_SIZE = 12

# Color settings
DEFAULT_TEXT_COLOR = (0, 0, 0)  # Black
COLOR_PREVIEW_SIZE = 20

# Widget settings
ANGLE_CONTAINER_SIZE = (300, 70)
SPINBOX_WIDTH = 50
BUTTON_HEIGHT = 40

# UI text
PLACEHOLDER_TEXT = "Enter text here..."
FONT_LABEL = "Font:"
COLOR_BUTTON_TEXT = "Choose Color"
TEXT_SIZE_LABEL = "Text Size:"
TEXT_ANGLE_LABEL = "Text Angle:"
ADD_TEXT_BUTTON = "Add Text" 